# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake.exe

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/c/Development/Projects/libsteam

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/c/Development/Projects/libsteam

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Development/Projects/libsteam/CMakeFiles /cygdrive/c/Development/Projects/libsteam/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Development/Projects/libsteam/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libsteam-test

# Build rule for target.
libsteam-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libsteam-test
.PHONY : libsteam-test

# fast build rule for target.
libsteam-test/fast:
	$(MAKE) -f CMakeFiles/libsteam-test.dir/build.make CMakeFiles/libsteam-test.dir/build
.PHONY : libsteam-test/fast

#=============================================================================
# Target rules for targets named steam

# Build rule for target.
steam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 steam
.PHONY : steam

# fast build rule for target.
steam/fast:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/build
.PHONY : steam/fast

src/Steam2/authclient.o: src/Steam2/authclient.c.o
.PHONY : src/Steam2/authclient.o

# target to build an object file
src/Steam2/authclient.c.o:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/src/Steam2/authclient.c.o
.PHONY : src/Steam2/authclient.c.o

src/Steam2/authclient.i: src/Steam2/authclient.c.i
.PHONY : src/Steam2/authclient.i

# target to preprocess a source file
src/Steam2/authclient.c.i:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/src/Steam2/authclient.c.i
.PHONY : src/Steam2/authclient.c.i

src/Steam2/authclient.s: src/Steam2/authclient.c.s
.PHONY : src/Steam2/authclient.s

# target to generate assembly for a file
src/Steam2/authclient.c.s:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/src/Steam2/authclient.c.s
.PHONY : src/Steam2/authclient.c.s

src/Steam2/dsclient.o: src/Steam2/dsclient.c.o
.PHONY : src/Steam2/dsclient.o

# target to build an object file
src/Steam2/dsclient.c.o:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/src/Steam2/dsclient.c.o
.PHONY : src/Steam2/dsclient.c.o

src/Steam2/dsclient.i: src/Steam2/dsclient.c.i
.PHONY : src/Steam2/dsclient.i

# target to preprocess a source file
src/Steam2/dsclient.c.i:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/src/Steam2/dsclient.c.i
.PHONY : src/Steam2/dsclient.c.i

src/Steam2/dsclient.s: src/Steam2/dsclient.c.s
.PHONY : src/Steam2/dsclient.s

# target to generate assembly for a file
src/Steam2/dsclient.c.s:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/src/Steam2/dsclient.c.s
.PHONY : src/Steam2/dsclient.c.s

src/Steam2/serverclient.o: src/Steam2/serverclient.c.o
.PHONY : src/Steam2/serverclient.o

# target to build an object file
src/Steam2/serverclient.c.o:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/src/Steam2/serverclient.c.o
.PHONY : src/Steam2/serverclient.c.o

src/Steam2/serverclient.i: src/Steam2/serverclient.c.i
.PHONY : src/Steam2/serverclient.i

# target to preprocess a source file
src/Steam2/serverclient.c.i:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/src/Steam2/serverclient.c.i
.PHONY : src/Steam2/serverclient.c.i

src/Steam2/serverclient.s: src/Steam2/serverclient.c.s
.PHONY : src/Steam2/serverclient.s

# target to generate assembly for a file
src/Steam2/serverclient.c.s:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/src/Steam2/serverclient.c.s
.PHONY : src/Steam2/serverclient.c.s

src/Util/crypto.o: src/Util/crypto.c.o
.PHONY : src/Util/crypto.o

# target to build an object file
src/Util/crypto.c.o:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/src/Util/crypto.c.o
.PHONY : src/Util/crypto.c.o

src/Util/crypto.i: src/Util/crypto.c.i
.PHONY : src/Util/crypto.i

# target to preprocess a source file
src/Util/crypto.c.i:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/src/Util/crypto.c.i
.PHONY : src/Util/crypto.c.i

src/Util/crypto.s: src/Util/crypto.c.s
.PHONY : src/Util/crypto.s

# target to generate assembly for a file
src/Util/crypto.c.s:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/src/Util/crypto.c.s
.PHONY : src/Util/crypto.c.s

src/Util/socketutil.o: src/Util/socketutil.c.o
.PHONY : src/Util/socketutil.o

# target to build an object file
src/Util/socketutil.c.o:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/src/Util/socketutil.c.o
.PHONY : src/Util/socketutil.c.o

src/Util/socketutil.i: src/Util/socketutil.c.i
.PHONY : src/Util/socketutil.i

# target to preprocess a source file
src/Util/socketutil.c.i:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/src/Util/socketutil.c.i
.PHONY : src/Util/socketutil.c.i

src/Util/socketutil.s: src/Util/socketutil.c.s
.PHONY : src/Util/socketutil.s

# target to generate assembly for a file
src/Util/socketutil.c.s:
	$(MAKE) -f CMakeFiles/steam.dir/build.make CMakeFiles/steam.dir/src/Util/socketutil.c.s
.PHONY : src/Util/socketutil.c.s

test/test.o: test/test.c.o
.PHONY : test/test.o

# target to build an object file
test/test.c.o:
	$(MAKE) -f CMakeFiles/libsteam-test.dir/build.make CMakeFiles/libsteam-test.dir/test/test.c.o
.PHONY : test/test.c.o

test/test.i: test/test.c.i
.PHONY : test/test.i

# target to preprocess a source file
test/test.c.i:
	$(MAKE) -f CMakeFiles/libsteam-test.dir/build.make CMakeFiles/libsteam-test.dir/test/test.c.i
.PHONY : test/test.c.i

test/test.s: test/test.c.s
.PHONY : test/test.s

# target to generate assembly for a file
test/test.c.s:
	$(MAKE) -f CMakeFiles/libsteam-test.dir/build.make CMakeFiles/libsteam-test.dir/test/test.c.s
.PHONY : test/test.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... libsteam-test"
	@echo "... rebuild_cache"
	@echo "... steam"
	@echo "... src/Steam2/authclient.o"
	@echo "... src/Steam2/authclient.i"
	@echo "... src/Steam2/authclient.s"
	@echo "... src/Steam2/dsclient.o"
	@echo "... src/Steam2/dsclient.i"
	@echo "... src/Steam2/dsclient.s"
	@echo "... src/Steam2/serverclient.o"
	@echo "... src/Steam2/serverclient.i"
	@echo "... src/Steam2/serverclient.s"
	@echo "... src/Util/crypto.o"
	@echo "... src/Util/crypto.i"
	@echo "... src/Util/crypto.s"
	@echo "... src/Util/socketutil.o"
	@echo "... src/Util/socketutil.i"
	@echo "... src/Util/socketutil.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

